import React, { useState, useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [items, setItems] = useState([]);
  const [chartItems, setChartItems] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await axios.get(
        'https://api.covid19api.com/countries'
      );
      // console.log(response.data);
      setItems(response.data);
    };

    const fetchChartData = async () => {
      const results = await axios.get(
        'https://api.covid19api.com/total/country/united-states'
      );
      // console.log(results.data);
      const passData = await results.data;
      // console.log(passData.reverse());

      setChartItems(passData.reverse());
    };

    fetchChartData();
    fetchData();

  }, [])

  console.log(items);
  console.log(chartItems);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Covid-19 Tracker</h1>
      </main>
    </div>
  )
}
