import React, { useState, useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import StatePop from '../components/StatePop';

export default function Home() {

  const [items, setItems] = useState([]);
  // const [dataItems, setDataItems] = useState([]);
  const [chartItems, setChartItems] = useState([]);
  // const [test, setTest] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await axios.get(
        'https://api.covid19api.com/countries'
      );
      // console.log(response.data);
      setItems(response.data);
    };



    const fetchChartData = async () => {
      const results = await axios.get(
        'https://api.covid19api.com/total/country/united-states'
      );
      // console.log(results.data);
      const passData = await results.data;
      // console.log(passData.reverse());

      setChartItems(passData.reverse());


      // var requestOptions = {
      //   method: 'GET',
      //   redirect: 'follow'
      // };

      // fetch("https://covidtracking.com/api/states/daily", requestOptions)
      //   .then(response => response.text())
      //   .then(result => setTest(result))
      //   // .then(result => console.log(result))
      //   .catch(error => console.log('error', error));

    };




    fetchChartData();
    // fetchConData()
    fetchData();

  }, [])

  // const fetchConData = async (passCountry) => {
  //   console.log(passCountry)
  //   const response = await axios.get(
  //     'https://api.covid19api.com/live/country/south-africa/status/confirmed'
  //   );
  //   // console.log(response.data);
  //   setDataItems(response.data);

  // };

  // console.log(items);
  // console.log(chartItems);
  // console.log(test);

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid-19 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Covid-19 Tracker</h1>
        <StatePop results={items} dataRes={dataItems} fetchConData={fetchConData} />
      </main>
    </div>
  )
}
